### ISSUE TITLE
Using in production

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-csi/csi-driver-host-path#239]
Hello,
Is there any plans to make this a production quality driver? Or, this will remain as a non-production driver?

Thanks.

**Comment by pohly** [comment]
> Is there any plans to make this a production quality driver?

No.

Is there a need for it? What would be the advantage over the in-tree emptydir or hostpath volume types?

I guess it could be used to manage additional disks, but that raises all kinds of questions that don't have good answers (IMHO).

**Comment by tamalsaha** [comment]
We want to use local volume for running databases.

**Comment by aglitke** [comment]
I would also like to point this thread to https://github.com/kubevirt/hostpath-provisioner  This driver sees significant usage and combined with @tamalsaha 's previous comment I think there is a case for it.  It would be nice if we could all work together on a single driver instead of fragmenting.  Hostpath is preferred over local-volume for several reasons including the possibility of dynamic provisioning.  A CSI driver is superior because it is not deprecated technology and because CSI allows for snapshots and cloning.
