### ISSUE TITLE
Add leader election to deployment

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/csi-driver-host-path#46]
So that we can catch issues like
https://github.com/kubernetes-csi/external-attacher/pull/144

**Comment by pohly** [comment]
Do we need testing with *and* without leadership election? Probably yes, because those go through different code paths.

Testing with leadership election isn't going to be very realistic in the Prow CI because it creates a cluster with just one node. We'll execute some additional code paths, but not the actual leadership election. My preference would be to switch to a multi-node KinD cluster for all testing. It's the more realistic case.

**Comment by pohly** [comment]
Maintaining all these different deployments is going to become more complicated. Would it be useful to start generating them with kustomize?

I've done that in PMEM-CSI such that kustomize is only needed when editing the input files. Users and the CI still get complete deployment files. See https://github.com/intel/pmem-CSI/pull/234/commits/6037be55d8b67c620007a7272c56a62e47438c07 for details. It wouldn't be hard to move that over to csi-driver-host-path.

**Comment by msau42** [comment]
Long term I think a multi-node cluster would be great.

Regarding managing deployment, I'm fine with kustomize. I'm also biased because I use it for PD driver too, and it's been working decently well for testing various configs like alpha, stable, staging, dev

**Comment by pohly** [comment]
@msau42 what about testing with and without leadership election? Do you think we need to test both?

**Comment by zhucan** [comment]
Why need to add leader election to deployment for csi-driver-host-path? Maybe creating two pod in the same time but in different node
